export const ROUTES = [
  {
    order: 1,
    displayCondition: [],
    className: '',
    navigateTo: '/dashboard',
    title: '',
    icon: '',
    isActive: [],
    subMenus: [],
  },
 {
    order: 2,
    displayCondition: [],
    className: '',
    navigateTo: '/todo',
    title: '',
    icon: '',
    isActive: [],
    subMenus: [],
  },
  {
    order: 2,
    displayCondition: [],
    className: '',
    navigateTo: '/todo',
    title: '',
    icon: '',
    isActive: [],
    subMenus: [],
  },
];
